services:
  goproxy:
    build:
      context: .
    image: goproxy:local
    pull_policy: build
    ports:
      - "8081:8081"
    environment:
      LISTEN_ADDR: ":8081"
      CACHE_DIR: "/cache"
      CONFIG_FILE: "/config/config.yml"
      GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=/tmp/goproxy_known_hosts -o BatchMode=yes"
      GIT_TERMINAL_PROMPT: "0"
    volumes:
      - goproxy-cache:/cache
      - ./ssh:/ssh:ro,Z
      - ./config.yml:/config-source/config.yml:ro,Z

volumes:
  goproxy-cache:
