package main

import (
	"fmt"
	"net"
	"net/url"
	"os"
	"path/filepath"
	"strings"
)

const containerSSHDir = "/home/goproxy/.ssh"

type hostConfig struct {
	host     string
	ip       string
	insecure bool
}

func (config hostConfig) validate(index int) error {
	if err := validateSSHConfigToken(config.host); err != nil {
		return fmt.Errorf("host %d: bad host: %w", index, err)
	}
	if net.ParseIP(config.ip) == nil {
		return fmt.Errorf("host %d: bad ip %q", index, config.ip)
	}
	return nil
}

func prepareGitSSHCommand(cacheDir, gitSSHCommand string, hostConfigs []hostConfig, prefixMappings []prefixMapping) ([]prefixMapping, string, error) {
	rewrittenPrefixMappings, hasKeyFiles, err := rewriteKeyedPrefixMappings(prefixMappings)
	if err != nil {
		return nil, "", err
	}
	if len(hostConfigs) == 0 && !hasKeyFiles {
		return rewrittenPrefixMappings, gitSSHCommand, nil
	}

	sshConfigPath, err := filepath.Abs(filepath.Join(cacheDir, "ssh_config"))
	if err != nil {
		return nil, "", err
	}
	content, err := sshConfigContent(hostConfigs, prefixMappings)
	if err != nil {
		return nil, "", err
	}
	if err := os.WriteFile(sshConfigPath, []byte(content), 0o600); err != nil {
		return nil, "", err
	}

	gitSSHCommand = strings.TrimSpace(gitSSHCommand)
	if hasKeyFiles && gitSSHCommand != "" && gitSSHCommand != defaultGitSSHCommand {
		return nil, "", fmt.Errorf("key_file cannot be used with custom GIT_SSH_COMMAND")
	}
	if gitSSHCommand == "" || gitSSHCommand == defaultGitSSHCommand {
		return rewrittenPrefixMappings, "ssh -F " + shellQuote(sshConfigPath), nil
	}
	return rewrittenPrefixMappings, gitSSHCommand + " -F " + shellQuote(sshConfigPath), nil
}

func sshConfigContent(hostConfigs []hostConfig, prefixMappings []prefixMapping) (string, error) {
	var builder strings.Builder
	builder.WriteString("# Generated by goproxy from CONFIG_FILE.\n\n")

	hostOverrides := make(map[string]hostConfig, len(hostConfigs))

	for index, config := range hostConfigs {
		if err := config.validate(index + 1); err != nil {
			return "", err
		}
		hostOverrides[config.host] = config

		builder.WriteString("Host ")
		builder.WriteString(config.host)
		builder.WriteString("\n")
		builder.WriteString("  HostName ")
		builder.WriteString(config.ip)
		builder.WriteString("\n")
		builder.WriteString("  HostKeyAlias ")
		builder.WriteString(config.host)
		builder.WriteString("\n")
		if config.insecure {
			builder.WriteString("  StrictHostKeyChecking no\n")
			builder.WriteString("  UserKnownHostsFile /dev/null\n")
			builder.WriteString("  CheckHostIP no\n")
		}
		builder.WriteString("\n")
	}

	for index, mapping := range prefixMappings {
		if mapping.keyFile == "" {
			continue
		}
		if err := writeKeyedPrefixHost(&builder, index, mapping, hostOverrides); err != nil {
			return "", err
		}
	}

	builder.WriteString("Host *\n")
	builder.WriteString("  BatchMode yes\n")
	builder.WriteString("  StrictHostKeyChecking accept-new\n")
	builder.WriteString("  UserKnownHostsFile /tmp/goproxy_known_hosts\n")
	return builder.String(), nil
}

func writeKeyedPrefixHost(builder *strings.Builder, index int, mapping prefixMapping, hostOverrides map[string]hostConfig) error {
	if err := validateSSHKeyFile(mapping.keyFile); err != nil {
		return fmt.Errorf("prefix %d: bad key_file: %w", index+1, err)
	}
	sshURL, err := parseKeyedSSHPrefix(mapping.sshPrefix, index)
	if err != nil {
		return err
	}

	originalHost := sshURL.Hostname()
	hostName := originalHost
	insecure := false
	if override, ok := hostOverrides[originalHost]; ok {
		hostName = override.ip
		insecure = override.insecure
	}

	builder.WriteString("Host ")
	builder.WriteString(prefixKeyAlias(index))
	builder.WriteString("\n")
	builder.WriteString("  HostName ")
	builder.WriteString(hostName)
	builder.WriteString("\n")
	if sshURL.User != nil {
		if user := sshURL.User.Username(); user != "" {
			builder.WriteString("  User ")
			builder.WriteString(user)
			builder.WriteString("\n")
		}
	}
	if port := sshURL.Port(); port != "" {
		builder.WriteString("  Port ")
		builder.WriteString(port)
		builder.WriteString("\n")
	}
	builder.WriteString("  HostKeyAlias ")
	builder.WriteString(originalHost)
	builder.WriteString("\n")
	builder.WriteString("  IdentityFile ")
	builder.WriteString(containerSSHDir)
	builder.WriteString("/")
	builder.WriteString(mapping.keyFile)
	builder.WriteString("\n")
	builder.WriteString("  IdentitiesOnly yes\n")
	if insecure {
		builder.WriteString("  StrictHostKeyChecking no\n")
		builder.WriteString("  UserKnownHostsFile /dev/null\n")
		builder.WriteString("  CheckHostIP no\n")
	}
	builder.WriteString("\n")
	return nil
}

func rewriteKeyedPrefixMappings(prefixMappings []prefixMapping) ([]prefixMapping, bool, error) {
	rewritten := append([]prefixMapping(nil), prefixMappings...)
	hasKeyFiles := false
	for index, mapping := range rewritten {
		if mapping.keyFile == "" {
			continue
		}
		hasKeyFiles = true
		rewrittenSSHPrefix, err := rewriteSSHPrefixHost(mapping.sshPrefix, prefixKeyAlias(index), index)
		if err != nil {
			return nil, false, err
		}
		rewritten[index].sshPrefix = rewrittenSSHPrefix
	}
	return rewritten, hasKeyFiles, nil
}

func rewriteSSHPrefixHost(sshPrefix, host string, index int) (string, error) {
	sshURL, err := parseKeyedSSHPrefix(sshPrefix, index)
	if err != nil {
		return "", err
	}
	if port := sshURL.Port(); port != "" {
		sshURL.Host = net.JoinHostPort(host, port)
	} else {
		sshURL.Host = host
	}
	return sshURL.String(), nil
}

func parseKeyedSSHPrefix(sshPrefix string, index int) (*url.URL, error) {
	sshURL, err := url.Parse(sshPrefix)
	if err != nil {
		return nil, fmt.Errorf("prefix %d: bad ssh_prefix: %w", index+1, err)
	}
	if sshURL.Scheme != "ssh" || sshURL.Hostname() == "" {
		return nil, fmt.Errorf("prefix %d: key_file requires ssh_prefix with ssh:// URL", index+1)
	}
	if sshURL.ForceQuery || sshURL.RawQuery != "" || sshURL.Fragment != "" {
		return nil, fmt.Errorf("prefix %d: ssh_prefix must not contain query or fragment", index+1)
	}
	if err := validateSSHConfigToken(sshURL.Hostname()); err != nil {
		return nil, fmt.Errorf("prefix %d: bad ssh_prefix host: %w", index+1, err)
	}
	if port := sshURL.Port(); port != "" {
		if err := validateSSHConfigPort(port); err != nil {
			return nil, fmt.Errorf("prefix %d: bad ssh_prefix port: %w", index+1, err)
		}
	}
	if sshURL.User != nil {
		if _, hasPassword := sshURL.User.Password(); hasPassword {
			return nil, fmt.Errorf("prefix %d: ssh_prefix must not contain password", index+1)
		}
		if user := sshURL.User.Username(); user != "" {
			if err := validateSSHConfigToken(user); err != nil {
				return nil, fmt.Errorf("prefix %d: bad ssh_prefix user: %w", index+1, err)
			}
		}
	}
	return sshURL, nil
}

func prefixKeyAlias(index int) string {
	return fmt.Sprintf("goproxy-prefix-%d", index+1)
}

func validateSSHKeyFile(value string) error {
	if err := validateRelativePath(value); err != nil {
		return err
	}
	for _, char := range value {
		switch {
		case char >= 'a' && char <= 'z',
			char >= 'A' && char <= 'Z',
			char >= '0' && char <= '9',
			char == '.' || char == '-' || char == '_' || char == '/':
			continue
		}
		return fmt.Errorf("%q contains unsupported character %q", value, char)
	}
	return nil
}

func validateSSHConfigPort(value string) error {
	if value == "" {
		return fmt.Errorf("empty value")
	}
	for _, char := range value {
		if char < '0' || char > '9' {
			return fmt.Errorf("%q contains unsupported character %q", value, char)
		}
	}
	return nil
}

func validateSSHConfigToken(value string) error {
	if value == "" {
		return fmt.Errorf("empty value")
	}
	for _, char := range value {
		switch {
		case char >= 'a' && char <= 'z',
			char >= 'A' && char <= 'Z',
			char >= '0' && char <= '9',
			char == '.' || char == '-' || char == '_':
			continue
		}
		return fmt.Errorf("%q contains unsupported character %q", value, char)
	}
	return nil
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}
