package main

import (
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strings"
)

type hostConfig struct {
	host     string
	ip       string
	insecure bool
}

func (config hostConfig) validate(index int) error {
	if err := validateSSHConfigToken(config.host); err != nil {
		return fmt.Errorf("host %d: bad host: %w", index, err)
	}
	if net.ParseIP(config.ip) == nil {
		return fmt.Errorf("host %d: bad ip %q", index, config.ip)
	}
	return nil
}

func prepareGitSSHCommand(cacheDir, gitSSHCommand string, hostConfigs []hostConfig) (string, error) {
	if len(hostConfigs) == 0 {
		return gitSSHCommand, nil
	}

	sshConfigPath, err := filepath.Abs(filepath.Join(cacheDir, "ssh_config"))
	if err != nil {
		return "", err
	}
	content, err := sshConfigContent(hostConfigs)
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(sshConfigPath, []byte(content), 0o600); err != nil {
		return "", err
	}

	gitSSHCommand = strings.TrimSpace(gitSSHCommand)
	if gitSSHCommand == "" || gitSSHCommand == defaultGitSSHCommand {
		return "ssh -F " + shellQuote(sshConfigPath), nil
	}
	return gitSSHCommand + " -F " + shellQuote(sshConfigPath), nil
}

func sshConfigContent(hostConfigs []hostConfig) (string, error) {
	var builder strings.Builder
	builder.WriteString("# Generated by goproxy from CONFIG_FILE hosts.\n\n")

	for index, config := range hostConfigs {
		if err := config.validate(index + 1); err != nil {
			return "", err
		}

		builder.WriteString("Host ")
		builder.WriteString(config.host)
		builder.WriteString("\n")
		builder.WriteString("  HostName ")
		builder.WriteString(config.ip)
		builder.WriteString("\n")
		builder.WriteString("  HostKeyAlias ")
		builder.WriteString(config.host)
		builder.WriteString("\n")
		if config.insecure {
			builder.WriteString("  StrictHostKeyChecking no\n")
			builder.WriteString("  UserKnownHostsFile /dev/null\n")
			builder.WriteString("  CheckHostIP no\n")
		}
		builder.WriteString("  Include ~/.ssh/config\n")
		builder.WriteString("\n")
	}

	builder.WriteString("Host *\n")
	builder.WriteString("  BatchMode yes\n")
	builder.WriteString("  StrictHostKeyChecking accept-new\n")
	builder.WriteString("  UserKnownHostsFile /tmp/goproxy_known_hosts\n")
	return builder.String(), nil
}

func validateSSHConfigToken(value string) error {
	if value == "" {
		return fmt.Errorf("empty value")
	}
	for _, char := range value {
		switch {
		case char >= 'a' && char <= 'z',
			char >= 'A' && char <= 'Z',
			char >= '0' && char <= '9',
			char == '.' || char == '-' || char == '_':
			continue
		}
		return fmt.Errorf("%q contains unsupported character %q", value, char)
	}
	return nil
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}
